apiVersion: v1
kind: Service
metadata:
  name: api-one-service
  labels:
    app: training-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: training-app
